// <auto-generated />
using BookStore_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore_API.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    [Migration("20220818115303_DbFixAndSeeds")]
    partial class DbFixAndSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookStore_API.Data.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("HomeLatitude")
                        .HasColumnType("real");

                    b.Property<float>("HomeLongitude")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HomeLatitude = 26.643f,
                            HomeLongitude = 84.91426f,
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 2,
                            HomeLatitude = 41.76758f,
                            HomeLongitude = -72.70144f,
                            Name = "Suzanne Collins"
                        },
                        new
                        {
                            Id = 3,
                            HomeLatitude = 41.76758f,
                            HomeLongitude = -72.70144f,
                            Name = "Mark Twain"
                        });
                });

            modelBuilder.Entity("BookStore_API.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "Animal Farm is a beast fable, in form of satirical allegorical novellaby George Orwell",
                            Name = "Animal Farm"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Description = "Nineteen Eighty-Four is a dystopian social science fiction novel and cautionary tale",
                            Name = "1984"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Description = "The Hunger Games is a 2008 dystopian novel by the American writer Suzanne Collins",
                            Name = "The Hunger Games"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Description = "Catching Fire is a 2009 science fiction young adult novel by the American novelist Suzanne Collins, the second book in The Hunger Games series.",
                            Name = "Catching Fire"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Description = "The Adventures of Tom Sawyer is an 1876 novel by Mark Twain about a boy growing up along the Mississippi River.",
                            Name = "The Adventures of Tom Sawyer"
                        });
                });

            modelBuilder.Entity("BookStore_API.Data.Book", b =>
                {
                    b.HasOne("BookStore_API.Data.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookStore_API.Data.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
