version: "3.4"
services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "7017:5017"
        networks:
            - intcom
        depends_on: 
          - migrations
          - db
        
    db:
        image: mcr.microsoft.com/mssql/server:2019-CU17-ubuntu-20.04
        environment:
          SA_PASSWORD: "Password@12345"
          ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        networks:
            - intcom
        depends_on: 
          - migrations
    migrations:
        build: 
          context: ./BookStore API
          dockerfile: Dockerfile
        networks:
            - intcom
networks:
  intcom:
    driver: bridge