version: "3.4"
services:
    api:
        image: cool8009/bookstore-api-sela
        ports:
          - "7017:5017"
        networks:
            - intcom
        depends_on: 
          - migrations
          - db
        
    db:
        image: mcr.microsoft.com/mssql/server:2019-CU17-ubuntu-20.04
        environment:
          SA_PASSWORD: "Password@12345"
          ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        networks:
            - intcom
        depends_on: 
          - migrations
    migrations:
        image: cool8009/bookstore-migrations-sela
        networks:
            - intcom
    web:
        image: cool8009/bookstore-sela
        ports:
            - "80:80"
        restart: always
networks:
  intcom:
    driver: bridge